"""empty message

Revision ID: 101189b62fca
Revises: f880b13adaa4
Create Date: 2017-12-07 12:32:05.609292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '101189b62fca'
down_revision = 'f880b13adaa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Followers')
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('track_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ip', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('Followers',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_from', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_to', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_from'], [u'Users.id'], name=u'Followers_ibfk_1', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['user_to'], [u'Users.id'], name=u'Followers_ibfk_2', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
